import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>API Test Zone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Testing API punya{" "}
          <a href="https://github.com/farrelaby?tab=repositories">Parrel</a>
        </h1>

        <p className={styles.description}>
          Selamat datang! <br /> Di web ini, kalian bisa bermain dengan protokol{" "}
          <code className={styles.code}>HTTP</code> sederhana!
        </p>

        <div className={styles.grid}>
          <Link href="/docu">
            <a className={styles.card}>
              <h2>Absensi &rarr;</h2>
              <p>Klik ini buat absen</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
